apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
spec:
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: msbeigiai/paymentservice:latest
        ports:
        - containerPort: 8081
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: config_url
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
  - port: 80
    targetPort: 8081

